apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-user
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: user-management
    namespaceSelector:
      matchNames:
        - green-energy-tracker
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 5s
