apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-agent-role
  namespace: green-energy-tracker
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]