apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard