apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-service
  namespace: green-energy-tracker
spec:
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: kafka-connect