apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center-pod
  namespace: green-energy-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
        - name: control-center
          image: confluentinc/cp-enterprise-control-center:latest
          ports:
            - containerPort: 9021
          envFrom:
            - configMapRef:
                name: control-center-config
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "4Gi"
              cpu: "2"
  restartPolicy: Always