apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-pod
  namespace: green-energy-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
            - containerPort: 9093
          envFrom:
            - configMapRef:
                name: kafka-config
            - secretRef:
                name: kafka-secret
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/kafka/data
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "1.5Gi"
              cpu: "1"
      volumes:
        - name: data-volume
          emptyDir: {}
  restartPolicy: Always