# kubernetes/nexus/deployment-nexus.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        runAsUser: 200
        runAsGroup: 200
        fsGroup: 200
      containers:
        - name: nexus
          image: sonatype/nexus3:3.67.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
            - containerPort: 5000
              name: registry
          env:
            - name: INSTALL4J_ADD_VM_PARAMS
              value: |
                -Xms600m
                -Xmx600m
                -XX:MaxDirectMemorySize=512m
                -XX:+UnlockExperimentalVMOptions
                -XX:+UseCGroupMemoryLimitForHeap
                -Djava.util.prefs.userRoot=/nexus-data/javaprefs
            - name: NEXUS_SECURITY_RANDOMPASSWORD
              value: "false"
          livenessProbe:
            httpGet:
              path: /service/rest/v1/status
              port: http
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /service/rest/v1/status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "1.5"
              memory: "2.5Gi"
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data-pvc
