apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-pod
  namespace: green-energy-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:lts
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: sonarqube-config
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "1.5Gi"
              cpu: "500m"
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-pvc