apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: green-energy-tracker
data:
  CLUSTER_ID: r4zt_wrqTRuT7W2NJsB_GA
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092,EXTERNAL://kafka-service:29092
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_KRAFT_MODE: 'true'
  KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
  KAFKA_LOG_DIRS: /var/lib/kafka/data
  KAFKA_LOG_RETENTION_HOURS: '168'
  KAFKA_NODE_ID: '1'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
  KAFKA_PROCESS_ROLES: controller,broker
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
