apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-config
  namespace: green-energy-tracker
data:
  SCHEMA_REGISTRY_HOST_NAME: schema-registry-service
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-service.green-energy-tracker:9092
  SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085