apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management-config
  namespace: green-energy-tracker
data:
  SPRING_APPLICATION_NAME: user-management
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/green-energy-tracker
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: io.confluent.kafka.serializers.KafkaAvroSerializer
  SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_CACHE_CAPACITY: '1000'
  SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry-service:8085
  SPRING_KAFKA_TOPIC_USER_EVENTS: user-events
  SPRING_KAFKA_TOPIC_USER_EVENTS_DLQ: user-events-dlq