apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
  namespace: green-energy-tracker
spec:
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  selector:
    app: schema-registry
  type: ClusterIP