apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: green-energy-tracker
spec:
  ports:
    - name: external
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: internal
      protocol: TCP
      port: 9093
      targetPort: 9093
  selector:
    app: kafka
  type: ClusterIP