apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
spec:
  type: ClusterIP
  selector:
    app: nexus
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: registry
      port: 5000
      targetPort: 5000