apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: green-energy-tracker
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP