apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  labels:
    app: user-management
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
    prometheus.io/path: '/actuator/prometheus'
spec:
  selector:
    app: user-management
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP