apiVersion: v1
kind: ConfigMap
metadata:
  name: control-center-config
  namespace: green-energy-tracker
data:
  CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka-service:9092"
  CONTROL_CENTER_CONNECT_MYCLUSTER_CLUSTER: "http://kafka-connect-service:8083"
  CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT: "/connectors"
  CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry-service:8085"
  CONTROL_CENTER_AUDIT_LOG_BOOTSTRAP_SERVERS: "kafka-service:9092"
  CONTROL_CENTER_AUDIT_LOG_ENABLED: "true"
  CONTROL_CENTER_AUDIT_LOG_TOPIC: "confluent-audit-log-events"
  CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: "1"
  CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: "1"
  CONTROL_CENTER_METRICS_TOPIC_NUM_PARTITIONS: "1"
  CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: "1"
  CONTROL_CENTER_REPLICATION_FACTOR: "1"