apiVersion: v1
kind: Service
metadata:
  name: control-center-service
  namespace: green-energy-tracker
spec:
  ports:
    - protocol: TCP
      port: 9021
      targetPort: 9021
  selector:
    app: control-center
  type: ClusterIP