apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-rolebinding
  namespace: green-energy-tracker
subjects:
  - kind: ServiceAccount
    name: jenkins-agent
    namespace: green-energy-tracker
roleRef:
  kind: Role
  name: jenkins-agent-role
  apiGroup: rbac.authorization.k8s.io